apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gopher-slack-bot
  namespace: gopher-slack-bot
  labels:
    app: gopher-slack-bot
    version: ec1c2849cb3d9ea921503a1e1b70a1b91c50f3b9
  annotations:
    description: Gopher Slack Bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: gopher-slack-bot
      labels:
        app: gopher-slack-bot
      annotations:
        description: Gopher Slack Bot
    spec:
      containers:
      - name: gopher-slack-bot
        image: eu.gcr.io/gopher-slack-bot/bot:ec1c2849cb3d9ea921503a1e1b70a1b91c50f3b9
        resources:
          requests:
            cpu: 300m
            memory: 130Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        env:
          - name: GOPHERS_SLACK_BOT_NAME
            valueFrom:
              secretKeyRef:
                name: gophersecret
                key: botname
          - name: GOPHERS_SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gophersecret
                key: token
      restartPolicy: Always
      dnsPolicy: ClusterFirst
