apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gopher-slack-bot
  namespace: gopher-slack-bot
  labels:
    app: gopher-slack-bot
    version: ec1c2849cb3d9ea921503a1e1b70a1b91c50f3b9
  annotations:
    description: Gopher Slack Bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: gopher-slack-bot
      labels:
        app: gopher-slack-bot
      annotations:
        description: Gopher Slack Bot
    spec:
      containers:
      - name: gopher-slack-bot
        image: eu.gcr.io/gopher-slack-bot/bot:ec1c2849cb3d9ea921503a1e1b70a1b91c50f3b9
        ports:
         - name: healthz-port
           containerPort: 8081
           hostPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz-port
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz-port
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 300m
            memory: 130Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /datastore.json
          - name: GOPHERS_SLACK_BOT_NAME
            valueFrom:
              secretKeyRef:
                name: gophersecret
                key: botname
          - name: GOPHERS_SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gophersecret
                key: token
        volumeMounts:
          - name: datastore
            mountPath: /tmp
            readOnly: true
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
      volumes:
        - name: datastore
          secret:
            secretName: gopher-datastore
            items:
              key: file
              path: datastore.json
