kind: ReplicationController
apiVersion: v1
metadata:
  name: gopher-slack-bot
  namespace: gopher-slack-bot
  labels:
    app: gopher-slack-bot
    version: 0bcb15f5b766946abf4fd531f61678b3669352d6
  annotations:
    description: Gopher Slack Bot
spec:
  replicas: 1
  selector:
    app: gopher-slack-bot
    version: 0bcb15f5b766946abf4fd531f61678b3669352d6
  template:
    metadata:
      name: gopher-slack-bot
      labels:
        app: gopher-slack-bot
        version: 0bcb15f5b766946abf4fd531f61678b3669352d6
      annotations:
        description: Gopher Slack Bot
    spec:
        containers:
          - name: gopher-slack-bot
            image: eu.gcr.io/gopher-slack-bot/bot:0bcb15f5b766946abf4fd531f61678b3669352d6
            resources:
              requests:
                cpu: 400m
                memory: 200Mi
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: false
            env:
              - name: GOPHERS_SLACK_BOT_NAME
                valueFrom:
                  secretKeyRef:
                    name: gophersecret
                    key: botname
              - name: GOPHERS_SLACK_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: gophersecret
                    key: token
        restartPolicy: Always
        terminationGracePeriodSeconds: 1
        dnsPolicy: ClusterFirst
